### ISSUE TITLE
TODO (feature parity with https://github.com/hi-ogawa/ytsub)

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/ytsub-v2#1]
setup

- [x] webpack
  - [x] development
    - [x] ui hot reload
  - [x] production
- [x] typescript
- [x] prettier
- [x] testing
  - unit test
  - render test
  - [x] integration test (playwright)
- [x] deployment

app

- [x] material ui
  - [x] layout
  - [x] appbar
  - [x] breakpoint
  - [x] drawer
- [x] router
  - [x] better url parameter management
- [x] react-query
- ~redux~

features

- [x] preferred language setting
- [x] web share target
- [x] player interaction
- [x] watch history
- [x] bookmark
  - [x] mini player https://github.com/hi-ogawa/ytsub-v2/pull/28
- [x] auto scroll subtitles viewer https://github.com/hi-ogawa/ytsub-v2/pull/30

misc

- [x] fix hot reload failure due to service-worker.js
- [x] react query disable refetch
- [x] improve performance of large list
  - use tailwind css https://tailwindcss.com/docs/installation
